### ISSUE TITLE
 Improper use of require_login method instead of require_course_login

### ISSUE THREAD

**Issue by CrymSonir** [mudrd8mz/moodle-mod_poster#10]
Hello,

just a small contribution following a problem we encountered when using the plugin.

How to reproduce the issue :
- Put the poster activity in "hidden but accessible" on the home page of your platform
- Try to access the activity via the url link
- You cannot view activity unless you are authenticated
Note : Look like if you enable the "**autologinguests**" option it will bypass the problem but it shouldn't be necessary

The problem comes from an improper use of the require_login method instead of require_course_login :
https://github.com/mudrd8mz/moodle-mod_poster/blob/212f235af84643bc2fbbcbc0305ebcc627826bf5/view.php#L35

see the doc for more info about both method : 
https://docs.moodle.org/dev/Access_API#require_login.28.29
https://docs.moodle.org/dev/Access_API#require_course_login.28.29

**Comment by stefanscholz** [comment]
Fixed in 7.0.0
